spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatisplus?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    #    driver-class-name: com.mysql.jdbc.Driver
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driverClass: com.mysql.jdbc.Driver
    username: root
    password: root123


mybatis-plus:
  global-config:
    db-config:
      #      主键生成规则
      id-type: auto
      #      逻辑删除字段,或者在字段上直接加@TableLogic
      logic-delete-field: deleted
      #      逻辑删除值
      logic-delete-value: -1
      #      逻辑不删除值
      logic-not-delete-value: 1
  configuration:
    #    日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-prefix:


logging:
  level:
    com.example.jc.mybatispluslearn: info
    com.example.jc.mybatispluslearn.domain.mapper: warn
  file:
    name: target/mybatis-plus-learn.log
